// For an introduction to the Blank template, see the following documentation:
// http://go.microsoft.com/fwlink/?LinkId=232509
(function () {
    "use strict";

    WinJS.Binding.optimizeBindingReferences = true;

    var app = WinJS.Application;
    var activation = Windows.ApplicationModel.Activation;

    var data = [
    {
        "ProductID": 873,
        "Name": "Patch Kit/8 Patches",
        "ProductNumber": "PK-7098",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "0.8565",
        "ListPrice": "2.2900",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "S ",
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 37,
        "ProductModelID": 114,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "36e638e4-68df-411b-930a-daad57221aa6",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 922,
        "Name": "Road Tire Tube",
        "ProductNumber": "TT-R982",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 500,
        "ReorderPoint": 375,
        "StandardCost": "1.4923",
        "ListPrice": "3.9900",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "R ",
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 37,
        "ProductModelID": 93,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "ea442bd7-f69b-42d9-aa71-95e10b648f52",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 870,
        "Name": "Water Bottle - 30 oz.",
        "ProductNumber": "WB-H098",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "1.8663",
        "ListPrice": "4.9900",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "S ",
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 28,
        "ProductModelID": 111,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "834e8d1a-69a7-4c42-8b68-fa08d9ec9e5b",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 921,
        "Name": "Mountain Tire Tube",
        "ProductNumber": "TT-M928",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 500,
        "ReorderPoint": 375,
        "StandardCost": "1.8663",
        "ListPrice": "4.9900",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "M ",
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 37,
        "ProductModelID": 92,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "01a8c3fc-ed52-458e-a634-d5b6e2accfed",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 923,
        "Name": "Touring Tire Tube",
        "ProductNumber": "TT-T092",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 500,
        "ReorderPoint": 375,
        "StandardCost": "1.8663",
        "ListPrice": "4.9900",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "T ",
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 37,
        "ProductModelID": 94,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "179fec38-cab5-4a47-bcff-31cfc9e43a3c",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 877,
        "Name": "Bike Wash - Dissolver",
        "ProductNumber": "CL-9009",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "2.9733",
        "ListPrice": "7.9500",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "S ",
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 29,
        "ProductModelID": 119,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "3c40b5ad-e328-4715-88a7-ec3220f02acf",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 872,
        "Name": "Road Bottle Cage",
        "ProductNumber": "BC-R205",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "3.3623",
        "ListPrice": "8.9900",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "R ",
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 28,
        "ProductModelID": 113,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "601b1fe8-d4d0-4cfb-9379-29481cc05291",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 874,
        "Name": "Racing Socks, M",
        "ProductNumber": "SO-R809-M",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": "White",
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "3.3623",
        "ListPrice": "8.9900",
        "Size": "M",
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "R ",
        "Class": null,
        "Style": "U ",
        "ProductSubcategoryID": 23,
        "ProductModelID": 24,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "b9c7eb0a-1dd1-4a1d-b4c3-1dad83a8ea7e",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 875,
        "Name": "Racing Socks, L",
        "ProductNumber": "SO-R809-L",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": "White",
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "3.3623",
        "ListPrice": "8.9900",
        "Size": "L",
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "R ",
        "Class": null,
        "Style": "U ",
        "ProductSubcategoryID": 23,
        "ProductModelID": 24,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "c0a16305-74b7-4fae-b5c9-3e8bd0e44762",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 709,
        "Name": "Mountain Bike Socks, M",
        "ProductNumber": "SO-B909-M",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": "White",
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "3.3963",
        "ListPrice": "9.5000",
        "Size": "M",
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "M ",
        "Class": null,
        "Style": "U ",
        "ProductSubcategoryID": 23,
        "ProductModelID": 18,
        "SellStartDate": "2005-07-01T00:00:00",
        "SellEndDate": "2006-06-30T00:00:00",
        "DiscontinuedDate": null,
        "rowguid": "18f95f47-1540-4e02-8f1f-cc1bcb6828d0",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 710,
        "Name": "Mountain Bike Socks, L",
        "ProductNumber": "SO-B909-L",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": "White",
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "3.3963",
        "ListPrice": "9.5000",
        "Size": "L",
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "M ",
        "Class": null,
        "Style": "U ",
        "ProductSubcategoryID": 23,
        "ProductModelID": 18,
        "SellStartDate": "2005-07-01T00:00:00",
        "SellEndDate": "2006-06-30T00:00:00",
        "DiscontinuedDate": null,
        "rowguid": "161c035e-21b3-4e14-8e44-af508f35d80a",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 871,
        "Name": "Mountain Bottle Cage",
        "ProductNumber": "BC-M005",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "3.7363",
        "ListPrice": "9.9900",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "M ",
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 28,
        "ProductModelID": 112,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "684491de-63f8-4632-90e3-36773c4e63bd",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 846,
        "Name": "Taillights - Battery-Powered",
        "ProductNumber": "LT-T990",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "5.7709",
        "ListPrice": "13.9900",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "R ",
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 33,
        "ProductModelID": 108,
        "SellStartDate": "2006-07-01T00:00:00",
        "SellEndDate": "2007-06-30T00:00:00",
        "DiscontinuedDate": null,
        "rowguid": "3c617b87-50a5-434c-a0d3-22314b7027ee",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 712,
        "Name": "AWC Logo Cap",
        "ProductNumber": "CA-1098",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": "Multi",
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "6.9223",
        "ListPrice": "8.9900",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "S ",
        "Class": null,
        "Style": "U ",
        "ProductSubcategoryID": 19,
        "ProductModelID": 2,
        "SellStartDate": "2005-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "b9ede243-a6f4-4629-b1d4-ffe1aedc6de7",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 931,
        "Name": "LL Road Tire",
        "ProductNumber": "TI-R092",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 500,
        "ReorderPoint": 375,
        "StandardCost": "8.0373",
        "ListPrice": "21.4900",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "R ",
        "Class": "L ",
        "Style": null,
        "ProductSubcategoryID": 37,
        "ProductModelID": 88,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "15b569a6-d172-42c2-a420-62ab5946cc80",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 878,
        "Name": "Fender Set - Mountain",
        "ProductNumber": "FE-6654",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "8.2205",
        "ListPrice": "21.9800",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "M ",
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 30,
        "ProductModelID": 121,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "e6e76c7f-c145-4cad-a9e8-b1e4e845a2c0",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 844,
        "Name": "Minipump",
        "ProductNumber": "PU-0452",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": null,
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "8.2459",
        "ListPrice": "19.9900",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "S ",
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 36,
        "ProductModelID": 116,
        "SellStartDate": "2006-07-01T00:00:00",
        "SellEndDate": "2007-06-30T00:00:00",
        "DiscontinuedDate": null,
        "rowguid": "aaf7a076-9ee3-46bf-a69f-414d847e858b",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 952,
        "Name": "Chain",
        "ProductNumber": "CH-0234",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": "Silver",
        "SafetyStockLevel": 500,
        "ReorderPoint": 375,
        "StandardCost": "8.9866",
        "ListPrice": "20.2400",
        "Size": null,
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 1,
        "ProductLine": null,
        "Class": null,
        "Style": null,
        "ProductSubcategoryID": 7,
        "ProductModelID": 98,
        "SellStartDate": "2007-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "5d27e2a5-27ec-4ccb-ba2c-fc980ffe6708",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 858,
        "Name": "Half-Finger Gloves, S",
        "ProductNumber": "GL-H102-S",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": "Black",
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "9.1593",
        "ListPrice": "24.4900",
        "Size": "S",
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "S ",
        "Class": null,
        "Style": "U ",
        "ProductSubcategoryID": 20,
        "ProductModelID": 4,
        "SellStartDate": "2006-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "9e1db5c3-539d-4061-9433-d762dc195cd8",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    },
    {
        "ProductID": 859,
        "Name": "Half-Finger Gloves, M",
        "ProductNumber": "GL-H102-M",
        "MakeFlag": false,
        "FinishedGoodsFlag": true,
        "Color": "Black",
        "SafetyStockLevel": 4,
        "ReorderPoint": 3,
        "StandardCost": "9.1593",
        "ListPrice": "24.4900",
        "Size": "M",
        "SizeUnitMeasureCode": null,
        "WeightUnitMeasureCode": null,
        "Weight": null,
        "DaysToManufacture": 0,
        "ProductLine": "S ",
        "Class": null,
        "Style": "U ",
        "ProductSubcategoryID": 20,
        "ProductModelID": 4,
        "SellStartDate": "2006-07-01T00:00:00",
        "SellEndDate": null,
        "DiscontinuedDate": null,
        "rowguid": "9d458fd5-392d-4ab1-afef-6a5548e48858",
        "ModifiedDate": "2008-03-11T10:01:36.827"
    }
    ];

    function getNewFilterRange(e) {
        //e.value contains an array of two values for RadRangeSlider. 
        //e.value[0] is the lower border of the range and e.value[1] is the max value.
        var min = e.value[0];
        var max = e.value[1];

        var listView = document.getElementById("listView").winControl;
        listView.itemDataSource = SampleData.Products.createFiltered(function (p) { return p.ListPrice > min && p.ListPrice < max }).dataSource;
    };

    WinJS.Namespace.define("SampleData", {
        Products: new WinJS.Binding.List(data),
        //the RadRangeSlider change event handler. It calls the getNewFilterRange() function and marks 
        //it for processing, so the handler can be used in the mark up.
        SliderChangeHandler: WinJS.Utilities.markSupportedForProcessing(getNewFilterRange),
        FormatPrice: WinJS.Binding.converter(function (price) {
            var formatted = Telerik.Utilities.toString(parseFloat(price), "c2", "en-US");
            return formatted;
        })
    });

    app.onactivated = function (args) {
        if (args.detail.kind === activation.ActivationKind.launch) {
            if (args.detail.previousExecutionState !== activation.ApplicationExecutionState.terminated) {
                // TODO: This application has been newly launched. Initialize
                // your application here.
            } else {
                // TODO: This application has been reactivated from suspension.
                // Restore application state here.
            }
            args.setPromise(WinJS.UI.processAll());
        }
    };

    app.oncheckpoint = function (args) {
        // TODO: This application is about to be suspended. Save any state
        // that needs to persist across suspensions here. You might use the
        // WinJS.Application.sessionState object, which is automatically
        // saved and restored across suspension. If you need to complete an
        // asynchronous operation before your application is suspended, call
        // args.setPromise().
    };

    app.start();
})();
